more

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -30,6 +30,21 @@ jobs:
       - name: Format
         run: npm run format
 
+      - name: Check for Changes
+        id: check_changes
+        run: |
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "changes_detected=true" >> $GITHUB_OUTPUT
+          else
+            echo "changes_detected=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Fail for formatting issues without personal access token
+        if: steps.check_changes.outputs.changes_detected == 'true'
+        run: |
+          echo "Formatting changes are needed but couldn't be committed because the personal access token isn't available or this isn't a pull request."
+          exit 1
+
   lint:
     runs-on: ubuntu-24.04
     permissions:
